jedzodzywiaj/config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :categories
  resources :articles do
  	resources :comments
  end
  resources :comments
  
  devise_for :users
  root 'home#index'
  get 'home/about'

end

jedzodzywiaj/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def motivation
  end

  def teory
  end

  def products
  end

  def recipies
  end

  def tips
  end

end

jedzodzywiaj/app/helpers/home_helper.rb
module HomeHelper
end

jedzodzywiaj/app/views/home/_header.html.erb
<div class"menugorne">
<div class="navbarsmall" role="navigation">
    <!-- Collect the nav links, forms, and other content for toggling -->
      <ul>
        <li><%= link_to 'O PROJEKCIE', home_about_path, class: "linkmenu" %></li>
        <%if user_signed_in? %>
          <% if current_user.admin? %>
        <li><%= link_to 'DODAJ ARTYKUŁ', new_article_path, class: "linkmenu" %></li>
          <% end %>
        <li><%= link_to 'EDYCJA PROFILU', edit_user_registration_path, class: "linkmenu" %></li>
        <li><%= link_to 'WYLOGUJ', destroy_user_session_path, method: :delete, class: "linkmenu" %></li>
        <% else %>
        <li><%= link_to 'LOGOWANIE', new_user_session_path, class: "linkmenu" %></li>
        <li><%= link_to 'REJESTRACJA', new_user_registration_path, class: "linkmenu" %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
  </div><!-- /.container-fluid -->

<div class="logo"><%= link_to image_tag("logo.png") %></div>

<nav class="navbar" role="navigation">
  <div class="container-fluid">
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav ">
      <% Category.all.each do |category| %>
        <li><%= link_to category.name, articles_path(category: category.name),class: "linkmenu" %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>







	
		        
		    
      	
       
    
  	
        
  

jedzodzywiaj/app/views/home/about.html.erb
<div>
<p>Autorem niniejszego serwisu jest  Aleksandra Żurawska. <br>
Serwis ten stanowi integralną część pracy licencjackiej (kierunek: Elektroniczne Przetwarzanie Informacji), <br> przygotowanej pod kierunkiem dr. hab. Grzegorza Bilińskiego, prof. ASP,<br> na Wydziale Zarządzania i Komunikacji Społecznej Uniwersytetu Jagiellońskiego.</p>
</div>

jedzodzywiaj/app/views/home/index.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
    <button class="czytajwiecej">Czytaj więcej</button>
      <%= image_tag("banerwarzywka6.png", :alt => "rss feed") %>
      
      <div class="carousel-caption">
        <p></p>
      </div>
    </div>
    <div class="item">
      <%= image_tag("banerwarzywka6.png", :alt => "rss feed") %>
      <div class="carousel-caption">
        <p></p>
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Poprzedni</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Następny</span>
  </a>
</div>
<br>
<br>
<hr> 