jedzodzywiaj/config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :categories
  resources :articles do
  	resources :comments
  end
  resources :comments
  
  devise_for :users
  root 'home#index'
  get 'home/about'

end

jedzodzywiaj/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
  validates :user_id, presence: true  
end

jedzodzywiaj/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(params[:comment].permit(:body))
    if current_user
      @comment.update_attribute(:user_id,current_user.id)
    end
    redirect_to article_path(@article), notice: 'Komentarz został dodany.'

   # @comment = Comment.new(comment_params)

   # respond_to do |format|
   #   if @comment.save
   #     format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
   #     format.json { render :show, status: :created, location: @comment }
   #   else
   #     format.html { render :new }
  #      format.json { render json: @comment.errors, status: :unprocessable_entity }
   #   end
  #  end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Komentarz został dodany.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), notice: 'Komentarz został usunięty.'
#    respond_to do |format|
#       format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
#       format.json { head :no_content }
#     end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :user_id, :article_id)
    end
end

jedzodzywiaj/app/helpers/comments_helper.rb
module CommentsHelper
end

jedzodzywiaj/app/views/comments/_comment.html.erb
<p>
 <%= comment.created_at.strftime("%d %B %Y") %>
 </p>
 <p>
    <b>
    <% if comment.user_id  && comment.user_id != 0 %>
    <%= comment.user.email %> pisze: 
    </b>
    <% else %>

     <b>Anonim pisze: </b>
    <% end %>
  </p>
 

  <p>
    <%= comment.body %>
  </p>

  
  <% if comment.user == current_user %>
  <p>
  <%= link_to 'Usuń', [comment.article, comment],
 			   :method => :delete,
               data: {:confirm => 'Jesteś pewien?'} %>
  </p>

  <% end %>
<hr>

jedzodzywiaj/app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>

  <div class="form-group">
    <% f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  
  <div class="actions">
    <%= f.submit "Dodaj komentarz", class: 'btn btn-default' %>
  </div>
<% end %>

jedzodzywiaj/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

jedzodzywiaj/app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th>Article</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= comment.article %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

jedzodzywiaj/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

jedzodzywiaj/app/views/comments/show.html.erb
<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article.title %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>