jedzodzywiaj/config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :categories
  resources :articles do
  	resources :comments
  end
  resources :comments
  
  devise_for :users
  root 'home#index'
  get 'home/about'

end

jedzodzywiaj/app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category
  has_many :comments, :dependent => :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
  has_attached_file :image, :styles => { :medium => "500x500", :thumb => "100x100"}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

jedzodzywiaj/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    if params[:category]
      category = Category.find_by_name(params[:category])
      if category
        @articles = category.articles
      else
        @articles = []
      end
    else
      @articles = Article.all
    end
  end
  
  # GET /articles/1
  # GET /articles/1.json
  def show
    cookies[:last_article_id] = params[:id]
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Artykuł został dodany.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Artykuł został zaktualizowany.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Artykuł został usunięty.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :category_id, :image)
    end
end

jedzodzywiaj/app/helpers/articles_helper.rb
module ArticlesHelper
end

jedzodzywiaj/app/views/articles/_form.html.erb
<%= form_for @article, html: { multipart: true } do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :Tytuł%><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :Treść %><br>
    <%= f.cktext_area :content, rows: 10 %>
  </div>

  <div class="form-group">
  <%= f.label :Kategoria %><br>
  <%= f.select :category_id, options_for_select(Category.all.map{|s|[s.name, s.id]}), class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :image, "Zdjęcie" %><br>
    <%= f.file_field :image, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit "Dodaj artykuł", class: 'btn btn-default' %>
  </div>
<% end %>

jedzodzywiaj/app/views/articles/edit.html.erb
<div class="panel panel-default">
<div class="panel-heading">
<h1>Edytuj artykuł</h1>
</div>
<div class="panel-body">
<%= render 'form' %>
</div>
<div class="panel-footer">
<%= link_to 'Wyświetl', @article %> |
<%= link_to 'Wstecz', articles_path %>
</div>
</div>

jedzodzywiaj/app/views/articles/index.html.erb
 <div class="row">
<div class="transitions-enabled">
    <% @articles.each do |article| %> 
      <div class="box">  
              <div class="col-sm-6 col-md-4">
                   <div class="thumbnail">
                      <div class="thumbfoto">
                      <%= link_to image_tag(article.image), article, class: "miniaturka" %>
                      </div>
                      <div class="caption">
                      <p class="datadod">
                          <%= time_ago_in_words article.created_at, class: "datadod" %> temu 
                          </p>
                          <h3 class="artctitle"><%= link_to article.title, article, class: "artctitle" %></h3>
                          <%= raw article.content.truncate(140, separator: /\./) %>              
                          <%if user_signed_in? %>
                            <% if current_user.admin? %>
                            <p><%= link_to 'Edytuj', edit_article_path(article), class: "btn btn-default", role: "button" %>
                          <%= link_to 'Usuń', article, method: :delete, data: { confirm: 'Jesteś pewien?' },class: "btn btn-default", role: "button"  %> </p>
                          <% end %>
                          <% end %>

                        </div>
                    </div>
                </div>
        </div>
 
    <% end %>
</div>
       </div>      

jedzodzywiaj/app/views/articles/new.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
    <h1>Nowy Artykuł</h1>
    </div>
	<div class="panel-body">
	<%= render 'form' %>
	</div>
	<div class="panel-footer">
	<%= link_to 'Wstecz', articles_path %>
	</div>
</div>

jedzodzywiaj/app/views/articles/show.html.erb
<div class="panel panel-default widoczek">
	<div class="tloartshow">
			<div class="zdjecieart">
				<%= image_tag @article.image.url %><br>
			</div>

			<div class="artcontent">
	  				<h1 class="articletitle"><%= @article.title %></h1>

	  				<%= raw(@article.content) %>

		  				<div class="dateart">
		  					<p>Dodany <%= @article.created_at.strftime("%d %B %Y") %></p>
		  				</div>

  			</div>


	</div>			
</div>
  			

<div class="panel panel-default widoczek">
<div class="commentart">
					<h2> Liczba komentarzy: <%= @article.comments.count %></h2>
						<%= render @article.comments %>

					<h3>Podziel się swoją opinią:</h3>
						<%= render "comments/form" %>
			</div>
					<div class="panel-footer">
					<%if user_signed_in? %>
						<% if current_user.admin? %>
							<%= link_to 'Edytuj', edit_article_path(@article) %> 
						<% end %>
						<%= link_to 'Wstecz', articles_path %>
					<% else %>
						<%= link_to 'Wstecz', articles_path %>
					<% end %>

</div>